Repository swcarpentry/r-novice-gapminder-es, pull requests merged in 2018-04, with the labels that each got.

#40 update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type:enhancement, type:template and tools

#23 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type:template and tools

#42 Capital title
  _episodes_rmd/03-seeking-help_2.Rmd
Labels: help wanted, status:need more info

#43 data frame con minusculas
  _episodes_rmd/05-data-structures-part2.Rmd
Labels: type:formatting

#41 agregar signos de pregunta al titulo
  _episodes_rmd/13-dplyr.Rmd
Labels: status:need more info

#46 new files from `make serve`
  _episodes/01-rstudio-intro.md
  _episodes/02-project-intro.md
  _episodes/03-seeking-help_2.md
  _episodes/04-data-structures-part1.md
  _episodes/05-data-structures-part2.md
  _episodes/06-data-subsetting.md
  _episodes/07-control-flow.md
  _episodes/08-plot-ggplot2.md
  _episodes/09-vectorization.md
  _episodes/10-functions.md
  _episodes/11-writing-data.md
  _episodes/12-plyr.md
  _episodes/13-dplyr.md
  _episodes/14-tidyr.md
  _episodes/15-knitr-markdown.md
  _episodes/16-wrap-up.md
  _episodes_rmd/14-tidyr.Rmd
  fig/rmd-08-axis-scale-1.png
  fig/rmd-08-ch1-sol-1.png
  fig/rmd-08-ch2-sol-1.png
  fig/rmd-08-ch3-sol-1.png
  fig/rmd-08-ch4b-sol-1.png
  fig/rmd-08-ch5-sol-1.png
  fig/rmd-08-facet-1.png
  fig/rmd-08-lifeExp-layer-example-1-1.png
  fig/rmd-08-lifeExp-line-1.png
  fig/rmd-08-lifeExp-line-point-1.png
  fig/rmd-08-lifeExp-vs-gdpPercap-scatter-1.png
  fig/rmd-08-lifeExp-vs-gdpPercap-scatter2-1.png
  fig/rmd-08-lifeExp-vs-gdpPercap-scatter3-1.png
  fig/rmd-08-lm-fit-1.png
  fig/rmd-08-lm-fit2-1.png
  fig/rmd-08-theme-1.png
  fig/rmd-08-unnamed-chunk-2-1.png
  fig/rmd-09-ch2-sol-1.png
  fig/rmd-09-ch2-sol-2.png
  fig/rmd-13-unnamed-chunk-21-1.png
  fig/rmd-13-unnamed-chunk-22-1.png
  fig/rmd-13-unnamed-chunk-23-1.png
  fig/rmd-15-rmd_to_html_fig-1.png
Labels: type:formatting

#50 update body of index
  index.md
Labels: type:typo text

#52 add ? to title
  _episodes_rmd/11-writing-data.Rmd
Labels: type:typo text

#51 add capital C like all other titles
  _episodes_rmd/05-data-structures-part2.Rmd
Labels: type:typo text

#62 Create NEWS.md
  NEWS.md
Labels: type:enhancement

#68 Revision de episodios 2 y 3
  _episodes_rmd/02-project-intro.Rmd
  _episodes_rmd/03-seeking-help_2.Rmd
Labels: type:clarification, type:typo text

#73 Improve "Guardando datos" in spanish
  _episodes_rmd/11-writing-data.Rmd
Labels: type:clarification, type:formatting

#74 Revisión de lección 8 ggplot
  _episodes_rmd/08-plot-ggplot2.Rmd
Labels: type:typo text
